### PR TITLE
(feat): `SpatialData` wrapper

### PR DESCRIPTION
**Pull request by ilan-gold**
This is a first pass at a `SpatialData` wrapper.

Complete #331 for `SpatialData` via a static method (my preferred solution for 331).

Some todos:

- [ ] Work out coordinate system business (both here and JS)
- [x] Clean up AnnData API as well in alignment with what we want to see here, including re: #331

### CODE REVIEW

**Comment by LucaMarconato** [comment]
@ilan-gold could you please try installing from this PR? https://github.com/scverse/spatialdata/pull/545

**Comment by ilan-gold** [comment]
New problem @LucaMarconato  :( https://github.com/vitessce/vitessce-python/actions/runs/9250228613/job/25443383983?pr=333

**Comment by LucaMarconato** [comment]
I think this could get fixed after https://github.com/scverse/spatialdata/pull/570 is ready (it should be ready in 1-2 days).

**Comment by ilan-gold** [comment]
thanks a bunch @LucaMarconato !

**Comment by LucaMarconato** [comment]
The PR is now ready for review. Can you please check if it fixes the issues in this PR @ilan-gold?

**Comment by LucaMarconato** [comment]
I made some recent commits in the last hour; unless you tried one of those commits that didn't make the CI status green (now it's green again), it seems that the bug remains. Could you please isolate a short code snippet to reproduce this bug? I can have a look at it later (the error message in the CI is something I haven't encountered so far).

**Comment by ilan-gold** [comment]
@LucaMarconato just needed to cache bust i guess.  fixed now!

**Comment by LucaMarconato** [comment]
Ah ok great to hear! I had also tagged you here, which should explain the source of the problem: https://github.com/scverse/spatialdata/pull/615.

**Comment by ilan-gold** [comment]
@keller-mark Fixing notebook, apologies

**Comment by ilan-gold** [comment]
@keller-mark The only thing happening here is the `obsSets` is not appearing in the component.  Also, selections only kind of working, generating a set, but not actually rendering the result on the image spots.....if you can't see anything immediately going on I'd be happy to investigate as a bug.  Thanks!

**Pull request closed without merging**
