### PR TITLE
Add Generic Data Conversion for Molecules, Cell Sets, and Cells

### PR DESCRIPTION
**Pull request by ilan-gold**
This PR adds generic classes for converting data to vitessce json.  I really only wanted the `Molecules` class for the portal work but I figured I'd go ahead and do the others, especially since they will likely be needed for loom as well.  I also added tests and was able to test this out locally in the notebook:
Screen Shot 2020-11-30 at 5 49 05 PM

I know this overlaps a bit with #6 so it's up to you how we should handle this.  It seems like #6 could use some of the functionality introduced here, but also the tests changed there so I'd be curious on your thoughts.

### CODE REVIEW

**Comment by keller-mark** [comment]
Instead of `converters.py` can we call the file `entities.py`? I think of converters as converting from one file type to another. This seems more like adding classes that represent visualize-able entities (cells, cell sets, etc) to help with manipulating the JSON-like data structures.

**Review by keller-mark — COMMENTED** [review]
Other than that minor name change, it looks good. Thanks for adding all of the documentation comments

**Comment by ilan-gold** [comment]
@keller-mark One thing that occurred to me last night is future-proofing this.  We have `.json` but in the future we could have `.arrow` as well (thinking of `molcules` here).  Do you think we should append/prepend all the methods with `json`?  Maybe add an argument that for now will just be ignored like `type="json"`?

**Comment by keller-mark** [comment]
I have wondered about this as well. I think it is ok to merge as-is now and then generalize later once we find that we need the arrow functionality, since these classes are intended to be used internally (not included on the documentation site).

**Pull request merged**
