### PR TITLE
Zarr for AnnData 

### PR DESCRIPTION
**Pull request by ilan-gold**
Here we use Zarr for AnnData, supporting both local anndata objects and remote (zarr) stores. This breaks the current loom example because of a string parsing issue but I have opened an issue in [AnnData](https://github.com/theislab/anndata/issues/491) to make some progress on that.  In the meantime, I am going to clean this up and hopefully get a fix in for that issue so that the client can parse the loom object converted to anndata.

### CODE REVIEW

**Comment by ilan-gold** [comment]
Depends on https://github.com/vitessce/vitessce/pull/841 to work, but now all examples work.

**Comment by keller-mark** [comment]
What is the `adata_url` in `AnnDataWrapper` intended to do?

**Comment by ilan-gold** [comment]
> What is the `adata_url` in `AnnDataWrapper` intended to do?

It's for remote data - I added a notebook: https://github.com/vitessce/vitessce-python/pull/39/commits/39589bb0da8442511d12b7fae14afa953a351420

**Comment by keller-mark** [comment]
To support remote AnnData we can also add an options parameter to the existing `.add_file` method https://github.com/vitessce/vitessce-python/pull/40/files.

```py
vc = VitessceConfig(name='PBMC Reference')
dataset = (
    vc.add_dataset(name='PBMC 3k')
        .add_file(
            url,
            dt.CELLS,
            ft.ANNDATA_CELLS_ZARR,
            {
                'mappings': {
                    'UMAP': {'key': 'obsm/X_umap', 'dims': [0, 1]},
                    'PCA': {'key': 'obsm/X_pca', 'dims': [0, 1]}
                },
                'factors': ['obs/louvain']
            }
        )
        .add_file(
            url,
            dt.CELL_SETS,
            ft.ANNDATA_CELL_SETS_ZARR,
            [{'groupName': 'Louvain', 'setName': 'obs/louvain'}]
        )
        .add_file(
            url,
            dt.EXPRESSION_MATRIX,
            ft.ANNDATA_EXPRESSION_MATRIX_ZARR,
            {'matrix': 'X'}
        )
)
umap = vc.add_view(dataset, cm.SCATTERPLOT, mapping="UMAP")
pca = vc.add_view(dataset, cm.SCATTERPLOT, mapping="PCA")
cell_sets = vc.add_view(dataset, cm.CELL_SETS)
genes = vc.add_view(dataset, cm.GENES)
heatmap = vc.add_view(dataset, cm.HEATMAP)
vc.layout((umap / pca) | ((cell_sets | genes) / heatmap));
```

For now I think having both approaches for supporting remote data are ok, especially since the Wrapper class method is more concise. Can you add comments about the new AnnDataWrapper constructor parameters, and specifically mention that `adata_url` may only be used with Zarr store URLs?

**Comment by ilan-gold** [comment]
Yes @keller-mark thanks for catching that.  I will definitely add docs.

**Review by keller-mark — APPROVED** [review]

**Pull request merged**
