### PR TITLE
Mccalluc/coverage

### LINKED ISSUE #154: Test coverage
With the work I've been doing to support Python 3.6, I've wondered about our test coverage. Probably just enable, and add a lot of file-ignore in the config, to start somewhere.

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #154 
- ... and ignore all the things that aren't covered right now.
- Remove redundant names on jobs

### CODE REVIEW

**Comment by keller-mark** [comment]
> ignore all the things that aren't covered right now.

Why ignore things? Don't we want an accurate coverage metric even if it might currently be low?

**Comment by mccalluc** [comment]
> > ignore all the things that aren't covered right now.
>
> Why ignore things? Don't we want an accurate coverage metric even if it might currently be low?

@keller-mark : Good question: This is subjective. There are ways of using test coverage that haven't worked for me:
- Measure test coverage, but don't tie CI pass/fail to it: In my experience, unless something is an explicit failure, we don't worry about it; we get used to warning messages, and the coverage metric just becomes more noise.
- Measure test coverage, and fail if coverage goes down: This is better: The idea is that coverage can be ratcheted up over time. I've seen two problems with this: Ratcheting up the coverage check becomes a chore, and unrelated refactors / reformattings can lower coverage. (ie: Splitting lines to improve readability can lower coverage.)

One alternative is what I've done in this PR: Add enough ignores (either at the line or file level) so that "coverage" is 100% ... Advantages:
- If untested code is added to a file which otherwise has good coverage, the author needs to add an ignore on the new lines... and may be prompted to test the new code.
- If an entire file has low coverage, it's entirely ignored, and a small bug fix doesn't need to get hung up because the testing infrastructure for that file is missing.
- Line and file ignores function as a TODO list, if a developer has spare cycles and wants to improve the codebase.
- We do lose a measurement of the _actual_ coverage, but I'm ok with that: We know that some code is more complicated or more important that other code -- Not everything needs the same level of scrutiny. In addition, just looking at the coverage doesn't tell you much about the quality of the tests -- Maybe the output checks aren't strong. There's a danger that the coverage because a metric we try to improve artificially.

**Comment by keller-mark** [comment]
Thanks for the explanations. Just made https://github.com/vitessce/vitessce-python/pull/177. Would you also be able to resolve the __init__.py conflicts (I think they are related to the import fixes that you previouly made for python 3.6)?

**Review by keller-mark — APPROVED** [review]

**Comment by mccalluc** [comment]
3.10 is failing because of missing coverage:
```
vitessce/__init__.py           24      8    67%   26-27, 36-37, 45-46, 53-54
```
These are lines like:
```
except ModuleNotFoundError as e:
    warn(f'Extra installs are necessary to use widgets: {e}')
```
With everything installed in 3.10, we don't go down those paths: Fix: I'll add more ignores.

**Pull request merged**
