### PR TITLE
Mccalluc/update notebook examples

### LINKED ISSUE #77: Is there a suggested order to explore `docs/notebooks/`? Perhaps not...
https://github.com/vitessce/vitessce-python/blob/master/docs/widget_examples.rst determines the listing order for the notebooks in the generated documentation... but if there's a definite order a new user should look at these, should that be captured in the [README.md](https://github.com/vitessce/vitessce-python/blob/master/docs/notebooks/README.md)? Or maybe the filenames could be numbered, so a jupyter user could just go down the list?

Somewhat related: How does the Jupyter user download the prerequisite data? #76

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #77. The renaming points out that `widget_imaging_segmentation.ipynb` is not referenced in the RST. Should it be added at the end of the list, or was there a reason to hold it out?

### CODE REVIEW

**Comment by keller-mark** [comment]
@ilan-gold added it here https://github.com/vitessce/vitessce-python/pull/72#issue-665085212
I think it would be good to add it to the list, I don't think there is any reason not to.

**Comment by mccalluc** [comment]
@keller-mark : I've totally lost the context on this. Does it serve any purpose, or should it be closed?

**Review by keller-mark — APPROVED** [review]
Yes, I think adding the number prefixes to the filenames is a good change. I just merged with master and added one more notebook to the PR.

**Comment by mccalluc** [comment]
Sorting out merge conflicts with renaming is more trouble than it's worth: I'll just make a new PR from scratch. Sorry to let this fall through the cracks.

**Pull request closed without merging**
