### PR TITLE
Add repr()

### PR DESCRIPTION
**Pull request by mccalluc**
I need to get a working environment before going much further (#64, #65), but wanted to sound out this approach. The [higher level goal](https://github.com/hubmapconsortium/portal-ui/pull/1877/files#diff-dd2fbe2b8309793c09f6b71a272310f0c8162df7b810882ef8ee469bd67e3378R160-R161) is to just output calls to the Wrapper constructors for the values of the notebook cells, preferably the outermost Wrapper, and it will recurse to generate the string.

`repr` is in general _not_ how you should do data serialization... but that's not we're doing: We want to explain what an object is (which _is_ a good use for `repr`)... and incidentally, it should be executable.

In the one example I looked at in portal-ui, it didn't seem that the Wrapper instance was modified after creation... but I'm not confident that that's generally true.

Filing this as draft. If this doesn't seem horrible, I'd like to 
- get my environment working, 
- turn on doctests in this repo,
- and add code like this to the other Wrapper classes.

### CODE REVIEW

**Review by keller-mark — APPROVED** [review]
Tested with this notebook: 
Screen Shot 2021-06-04 at 4 54 02 PM

**Comment by keller-mark** [comment]
Just merged https://github.com/vitessce/vitessce-python/pull/67 into master, would you be able to try following steps:

```
conda deactivate
conda env remove -n vitessce-jupyter-examples
```

```
# in docs/notebooks
conda env create -f environment.yml
conda list
```
Check that the version of JupyterLab is greater than 3.0.0
```
pip install -e ../..
cd ../../js
npm install
npm run build
cd ../docs/notebooks
jupyter labextension install ../../js
jupyter lab
```

**Comment by mccalluc** [comment]
(I'd like #70 to be merged before I merge this one: That brings in doc test machinery, so the test here would actually be run.)

**Comment by mccalluc** [comment]
@ilan-gold -- Could this much be merged? I have not personally confirmed that it actually works for each of the types, and it wouldn't be unreasonable to ask for that before going farther.

**Comment by ilan-gold** [comment]
@mccalluc Do you mean in the portal?  I think it would probably be good to try this out in one of the notebooks for some of them.  That should be pretty straightforward and should translate to the portal.  This seems fairly low-risk so even if it doesn't work as intended, the package probably won't "break"

**Comment by mccalluc** [comment]
Close in favor of #115.

**Pull request closed without merging**
